### ISSUE TITLE
Not working since "forEach" update

### ISSUE THREAD

**Issue by LisburnLad** [deanhume/lazy-observer-load#3]
The new "for" loops, added to get things working in Edge, due to its lack of "forEach", appears to have broken the code.

**Comment by deanhume** [comment]
Good spot - lemme have a look

**Comment by deanhume** [comment]
Hi @LisburnLad  - this should be fixed with the latest [commit](https://github.com/deanhume/lazy-observer-load/commit/782b8a012de1a5d1bf7febeaf6e0902ff0cccbb4)

I've tested using Browserstack for Edge 14 & 15, but not sure if that is the best way to test. Do you mind giving it a run through and letting me know if it works and Ill close this?

**Comment by LisburnLad** [comment]
Hi Dean,


Everything seems to be fine now - both the downloaded code and your "working" example now both work, so I can see the burger and chips. (tested in Chrome & Edge)


Thanks for fixing.


Cheers,

Steve



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by deanhume** [comment]
Hooray for 🍔  and 🍟  !!!
